import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "./layouts";
import localFont from 'next/font/local'


const gilroy = localFont({
  src: [
    { path: 'public/fonts/Gilroy-Regular.woff', weight: '400', style: 'normal' },
    { path: 'public/fonts/gilroy-medium.ttf',  weight: '400', style: 'normal' },
    { path: 'public/fonts/Gilroy-Bold.woff2',    weight: '700', style: 'normal' },
  ],
  variable: '--font-gilroy',
  display: 'swap',
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PN-Landing-Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gilroy.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
